/**
 *
 * $Id$
 */
package tosca.validation;

import org.eclipse.emf.common.util.EList;

import tosca.Attribute;
import tosca.Interface;
import tosca.Property;

/**
 * A sample validator interface for {@link tosca.Relationship}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface RelationshipValidator {
    boolean validate();

    boolean validateType(String value);
    boolean validateInterfaces(EList<Interface> value);
    boolean validateProperties(EList<Property> value);
    boolean validateAttributes(EList<Attribute> value);
    boolean validateSource_interfaces(EList<Interface> value);
    boolean validateTarget_interfaces(EList<Interface> value);
    boolean validateTarget(String value);
    boolean validateRelationship_name(String value);
}
