/**
 *
 * $Id$
 */
package tosca.validation;

import org.eclipse.emf.common.util.EList;

import tosca.Group;
import tosca.Import;
import tosca.NodeTemplate;
import tosca.Parameter;
import tosca.Policy;
import tosca.Relationship;

/**
 * A sample validator interface for {@link tosca.TopologyTemplate}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface TopologyTemplateValidator {
    boolean validate();

    boolean validateTosca_definitions_version(String value);
    boolean validateImports(EList<Import> value);
    boolean validateOutputs(EList<Parameter> value);
    boolean validateInputs(EList<Parameter> value);
    boolean validateNodeTemplates(EList<NodeTemplate> value);
    boolean validateRealtionships(EList<Relationship> value);
    boolean validateGroups(EList<Group> value);
    boolean validatePolicies(EList<Policy> value);
    boolean validateDescription(String value);
}
