/*
 * generated by Xtext 2.10.0
 */
package it.polimi.dice.dicer.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractToscaDslScopeProvider extends DelegatingScopeProvider {
}
