/**
 * generated by Xtext 2.10.0
 */
package it.polimi.dice.dicer;

import it.polimi.dice.dicer.ToscaDslStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class ToscaDslStandaloneSetup extends ToscaDslStandaloneSetupGenerated {
  public static void doSetup() {
    ToscaDslStandaloneSetup _toscaDslStandaloneSetup = new ToscaDslStandaloneSetup();
    _toscaDslStandaloneSetup.createInjectorAndDoEMFRegistration();
  }
}
