/**
 * generated by Xtext 2.10.0
 */
package it.polimi.dice.dicer;

import it.polimi.dice.dicer.AbstractToscaDslRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class ToscaDslRuntimeModule extends AbstractToscaDslRuntimeModule {
}
