/**
 * generated by Xtext 2.10.0
 */
package it.polimi.dice.dicer.validation;

import it.polimi.dice.dicer.validation.AbstractToscaDslValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class ToscaDslValidator extends AbstractToscaDslValidator {
}
