/*
 * generated by Xtext 2.10.0
 */
package it.polimi.dice.dicer.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class ToscaDslAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("it/polimi/dice/dicer/parser/antlr/internal/InternalToscaDsl.tokens");
	}
}
